//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Activities.Calculadora {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.Activities.Calculadora.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Simple calculator activity used as an example.
        /// </summary>
        public static string Calculator_Description {
            get {
                return ResourceManager.GetString("Calculator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculator.
        /// </summary>
        public static string Calculator_DisplayName {
            get {
                return ResourceManager.GetString("Calculator_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Number.
        /// </summary>
        public static string Calculator_FirstNumber_DisplayName {
            get {
                return ResourceManager.GetString("Calculator_FirstNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input the first number.
        /// </summary>
        public static string Calculator_FirstNumber_Tooltip {
            get {
                return ResourceManager.GetString("Calculator_FirstNumber_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Result.
        /// </summary>
        public static string Calculator_Result_DisplayName {
            get {
                return ResourceManager.GetString("Calculator_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The result by applying the selected operation to the two input numbers.
        /// </summary>
        public static string Calculator_Result_Tooltip {
            get {
                return ResourceManager.GetString("Calculator_Result_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Second Number.
        /// </summary>
        public static string Calculator_SecondNumber_DisplayName {
            get {
                return ResourceManager.GetString("Calculator_SecondNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Input the second number.
        /// </summary>
        public static string Calculator_SecondNumber_Tooltip {
            get {
                return ResourceManager.GetString("Calculator_SecondNumber_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation.
        /// </summary>
        public static string Calculator_SelectedOperation_DisplayName {
            get {
                return ResourceManager.GetString("Calculator_SelectedOperation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the operation to be applied to the two input numbers.
        /// </summary>
        public static string Calculator_SelectedOperation_Tooltip {
            get {
                return ResourceManager.GetString("Calculator_SelectedOperation_Tooltip", resourceCulture);
            }
        }
    }
}
